### ISSUE TITLE
Consulta sobre desplegar tablas

### ISSUE THREAD

**Issue by Facundobarrionuevo** [ModernizacionMuniCBA/presupuesto-cordoba-2017#12]
Observaciones/Consulta

Las tablas tienen todas (Las de ingreso y las de gasto), no así las de ejecuciones del gasto ni las de presupuesto participativo, partidas primarias y luego tiene varias partidas secundarias (con varios niveles de profundidad). Las partidas primarias están siempre pintadas con colores. Mi consulta es si es viable o qué tan complejo puede ser el usuario vea la tabla sólo con las partidas principales y que él deba hacer un click para desplegar la partida principal que desee y ver todo el resto de las partidas secundarias que tiene esa principal. Pensando que sólo pueda hacer un clinck por partida principal, que una vez dentro de ella ya me muestre todo, lo que hoy se ve por defecto.

A modo de ejemplo y antes que sea un ticket me gustarla saber si se puede, porque no a todas las tablas dentro de ingresos o gastos me gustaría hacerle esto, sólo a algunas, dos o tres como mucho.

Ejemplo, la tabla de gastos totales que hay en este link:

https://modernizacionmunicba.github.io/presupuesto-cordoba-2017/gastos.html

![image](https://user-images.githubusercontent.com/20156968/30715749-cd34702c-9eed-11e7-9697-2c06f6b5b0b9.png)

**Comment by florenperetti** [comment]
Ahora voy a hacer unas pruebas para probar esto, quizás no sea muy complicado.

Mientras tanto, en la rama de cambios ya hice push de los tickets del #6 al #11 para que revises. Capaz que con el de los botones haya hecho un poco de lío, avisame cualquier cosa en el ticket que corresponda.

En un rato te aviso por esto.

**Comment by florenperetti** [comment]
Ya hice un push para que veas en esa tabla como queda. Si te parece bien hago eso mismo con las demás.

**Comment by Facundobarrionuevo** [comment]
Hola Flor. Vi lo que hiciste en las tablas, me gustó!

Podemos agregar algún signo más o algo que haga intuitivo al usuario que puede desplegar?

![image](https://user-images.githubusercontent.com/20156968/30750035-b04f411e-9f8b-11e7-9ab6-bdafda64d59c.png)

En otro ticket te paso qué tablas que me gustaría que tengas este desplegable.

Gracias,
