### ISSUE TITLE
Actualizar la base de datos que usa la viz de gastos

### ISSUE THREAD

**Issue by Facundobarrionuevo** [ModernizacionMuniCBA/presupuesto-cordoba-2017#15]
Necesitamos actualizar los números de la visualización de gastos.

![captura de pantalla 2017-09-24 a la s 20 19 08](https://user-images.githubusercontent.com/20156968/30787741-0ab7bb0a-a166-11e7-90a2-4f75899c76a3.png)

Yo no sé de donde toma datos esa visualización.

La cuestión es que actualicé los números totales y la tabla de abajo ya toma los nuevos números.

Si no me explico bien hablamos con @avdata99 que él sabe que hay que hacer.

Nuevos gatos:

https://docs.google.com/spreadsheets/d/11UGXTNvmaOezQNpFXxMXps_gT7kwEP08YeMdcz4wKXo/edit#gid=0

**Comment by avdata99** [comment]
Avisame cualquier duda Flor.
La tabla de abajo ya está actualizada, hay que actualizar el gráfico de arriba

**Comment by florenperetti** [comment]
Ya se estaban usando esos datos, tanto para la tabla como para el gráfico (se generan ambos a la vez, a partir de que se carga ese sheet). Avísenme si ven alguna inconsistencia en particular, yo creo que está todo ok.
