### ISSUE TITLE
Borrar Los gráficos de Tortas y Reemplazarlos por uno de Barras

### ISSUE THREAD

**Issue by Facundobarrionuevo** [ModernizacionMuniCBA/presupuesto-cordoba-2017#17]
Flor hay que borrar estos gráficos de tortas. Están bien hechos pero a Economía no les gusta los números que se muestran.

![captura de pantalla 2017-09-24 a la s 21 41 32](https://user-images.githubusercontent.com/20156968/30788350-61070b22-a171-11e7-9460-0f2f7384c7aa.png)

Vamos a mostrar el Resultado Económico del 2017 y de los años anteriores.

Flor vos decime si lo que te pido es muy complejo de hacer con total libertad.

Vamos a poner un gráfico de barras.

![captura de pantalla 2017-09-24 a la s 21 43 55](https://user-images.githubusercontent.com/20156968/30788354-7d9242a2-a171-11e7-830b-cf306aef09b1.png)

Este gráfico de barras deberá tomar datos del archivo "Resultado Económico" dentro del drive:

https://docs.google.com/spreadsheets/d/1bb72z4oCul0FWPDfoMoV_pfI_pbzGbQO7PT-Ukqm94o/edit#gid=780089189

Tienen 5 datos, 1 por año.

Ahora me gustaría que al lado del gráfico haya un botón que me permita mostrar el mismo gráfico pero con otros 5 datos. Estos otros 5 datos están también en el excel dentro de drive.

![captura de pantalla 2017-09-24 a la s 21 46 28](https://user-images.githubusercontent.com/20156968/30788378-dbec4f3c-a171-11e7-8b48-a6adbcdfcf43.png)

Cada uno de estos dos conjuntos de datos se diferencian en que uno contienen los intereses de deuda y los otros no los contemplan.

Por defecto me debería mostrar "Con intereses de la deuda" y debería tener un botón que me permita ver el mismo resultado económico pero "Sin los intereses de la deuda". Permitiendo al usuario ver cualquiera de los dos conjuntos de datos haciendo clink en botón.

Sería bueno que cuando las barras del gráfico cambien lo hagan con un pequeño movimiento lento, apreciable por el usuario, se esta manera se puede apreciar como cambian los datos.

Luego debajo de este gráfico de barras hay una nota y un texto que poner (Están en el excel)

![captura de pantalla 2017-09-24 a la s 21 50 43](https://user-images.githubusercontent.com/20156968/30788413-760e3062-a172-11e7-84e9-e32ea846b06e.png)

Después de este texto viene la tabla que está ya en la we tal cual está.

Avisame que tan viable o complicado es hacer esto flor, gracias.

**Comment by florenperetti** [comment]
Se podrá subir la tabla a la primera celda? Porque me está tirando un error, no me deja tomar los datos de esa tabla y no se si es por eso, están los gráficos primero.

**Comment by avdata99** [comment]
Facu esta cambiando los datos



Al parecer no funciona todo. Dejo esto como referencia
Pasar a CSV (una página en particular)
https://docs.google.com/feeds/download/spreadsheets/Export?key={key}&exportFormat={format}&gid={gid}
Ambas cosas (KEY y GUID) se ven en la URL

Pasar a JSON
https://spreadsheets.google.com/feeds/list/{key}/od6/public/values?alt=json
https://spreadsheets.google.com/feeds/{feed}/{key}/{guid}/public/basic?alt=json
feed = list o cells

[Ejemplo](https://github.com/ModernizacionMuniCBA/presupuesto-cordoba-2017/blob/3a0c128d8e57d9f0b3439223b5533d8d72051593/assets/js/faltasGrapher.js#L2)
https://spreadsheets.google.com/feeds/list/1ul8x07sCDmok1DujucaLyN-aWxpAXAXwlw8X2ixmvZc/od6/public/values?alt=json

https://spreadsheets.google.com/feeds/list/1bb72z4oCul0FWPDfoMoV_pfI_pbzGbQO7PT-Ukqm94o/780089189/public/values?alt=json

Más info
https://developers.google.com/sheets/guides/concepts?hl=es-419

Explicaciones del error
https://stackoverflow.com/questions/24531351/retrieve-google-spreadsheet-worksheet-json

**Comment by florenperetti** [comment]
Ya encontré el parámetro, cambió de od6 a ocwg0jj, quedó así el link:
https://spreadsheets.google.com/feeds/list/1bb72z4oCul0FWPDfoMoV_pfI_pbzGbQO7PT-Ukqm94o/ocwg0jj/public/values?alt=json

Ya puedo tomar los datos 👍

**Comment by florenperetti** [comment]
Lista una primera versión como para revisar.
