### ISSUE TITLE
Sumar valor al gráfico de torta de Pto participativo

### ISSUE THREAD

**Issue by Facundobarrionuevo** [ModernizacionMuniCBA/presupuesto-cordoba-2017#19]
Necesito que el gráfico de torta de presupuesto participativo me muestre lo mismo que me muestra el gráfico de torta del gasto por finalidad y función.
Actualmente sólo me muestra el %, falta el valor.

![captura de pantalla 2017-09-24 a la s 22 37 51](https://user-images.githubusercontent.com/20156968/30789063-3dd4ec8e-a179-11e7-8505-9d5024f55af1.png)

Debería ser así:

![captura de pantalla 2017-09-24 a la s 22 40 03](https://user-images.githubusercontent.com/20156968/30789076-546a21e4-a179-11e7-870d-2010b1899a02.png)

**Comment by florenperetti** [comment]
Perdón, no se si te referís a que el gráfico tiene que ser literalmente como el segundo, con los mismos datos (personal, servicios, etc), o si solamente hay que agregarle el valor al gráfico actual.

**Comment by Facundobarrionuevo** [comment]
Hola Flor. Hay que hacer que cuando paso el mause se vean el % y el valor nominal, actualmente sólo me deja ver el %.

El gráfico de abajo (el de gastos corrientes) te lo puse a modo de ejemplo nomás.
