### ISSUE TITLE
Cambios en la Viz de Recurso Económico

### ISSUE THREAD

**Issue by Facundobarrionuevo** [ModernizacionMuniCBA/presupuesto-cordoba-2017#20]
![image](https://user-images.githubusercontent.com/20156968/30829024-0280ddd0-a216-11e7-9de6-cffd6a9fed86.png)

La visualización está genial.

Necesito un par de cambios:

En el eje de las ordenadas donde dice valor, debería decir: **Millones de pesos**

En el eje de las abscisas Ampliar el tamaño de año, separarlo muy poquito y ponerlo en negrita:
(que el tamaño, separado y negrita sea lo mismo para el título del eje de las ordenadas)

![image](https://user-images.githubusercontent.com/20156968/30829267-b9e4f8da-a216-11e7-9918-adab92e84afa.png)

Que el título del gráfico esté centrado:

![image](https://user-images.githubusercontent.com/20156968/30829434-22d453f4-a217-11e7-831b-0d1dcbda577a.png)

Que desaparezcan las cuadrículas del fondo.

Que los valores que figuran en cada barra al posar el mause arriba digan por ejemplo: $ 766 millones
o sea agregar el signo pesos y la palabra millones.

**Comment by florenperetti** [comment]
Todavía no logré darle más espacio a las etiquetas de los ejes, pero ya está todo lo demás. Si después de estos cambios tenés alguna otra sugerencia avisame y más tarde lo reviso.
