### ISSUE TITLE
Olvidé cambiar un título

### ISSUE THREAD

**Issue by Facundobarrionuevo** [ModernizacionMuniCBA/presupuesto-cordoba-2017#26]
Olvidé este título perdón!

Está todo bien!

![image](https://user-images.githubusercontent.com/20156968/30879575-247a4a50-a2d6-11e7-973e-67e0fdb3d721.png)

Donde dice Porc. de ejecución, debería decir: **Ejecución Parcial/Ejecución Total**

**Comment by florenperetti** [comment]
No hay problema! Ya está corregido.
