### ISSUE TITLE
Hay un error importante en presupuesto participativo (Grafico)

### ISSUE THREAD

**Issue by Facundobarrionuevo** [ModernizacionMuniCBA/presupuesto-cordoba-2017#27]
El gráfico de torta tiene los mismos numeros que la tabla de abajo. 
Ahora el grafico me muestra datos erroneos. Me muestra los % bien pero los valores nominales mal.

Por ejemplo, para infraestructura:

![captura de pantalla 2017-09-26 a la s 20 17 08](https://user-images.githubusercontent.com/20156968/30888595-b30a514a-a2f7-11e7-9400-a477d4c1abb6.png)

Me pone que tiene el 56% y el valor de $9.335.082.499

Cuando en la tabla de abajo infraestructura tiene:

![captura de pantalla 2017-09-26 a la s 20 18 48](https://user-images.githubusercontent.com/20156968/30888629-ed28fcaa-a2f7-11e7-8cea-62a7f960ede1.png)

Me dice que el valor es igual a 56% y $93.343.661. Este es el valor correcto, no sé porque el gráfico de torta me pone otro valor nominal.

**Comment by avdata99** [comment]
Un ticket si el LINK a donde se ve el error debería ser penado con la pena capital precedida de alguna sesión de tortura.

https://modernizacionmunicba.github.io/presupuesto-cordoba-2017/presupuesto-participativo.html

Ahora trato de ver que es

**Comment by florenperetti** [comment]
Básicamente hice un refactor de ese archivo, estaba tomando mal los datos yo. Ya quedó ok me parece.

**Comment by avdata99** [comment]
Yo los veo iguales.
GENIA FLOR.
Cierro el ticket, si ves algo mas a arreglar re-abrilo facu

**Comment by Facundobarrionuevo** [comment]
Genia flor!
