### ISSUE TITLE
Salta error

### ISSUE THREAD

**Issue by Facundobarrionuevo** [ModernizacionMuniCBA/presupuesto-cordoba-2017#9]
Cambio 4)

Al hacer clic en EJECUCIONES PRESUPUESTARIAS desde los círculos salta un error. No obstante al entrar desde el menú del header funciona perfectamente.

Igual en el loop general nada va a ir con sonido así q está bien lo q nos mande

**Comment by florenperetti** [comment]
Me podrías pasar una captura del error? porque ingreso desde el círculo y veo todo ok. Gracias!

**Comment by Facundobarrionuevo** [comment]
Me confundí de imagen y no me di cuenta.

Va el error...


![image](https://user-images.githubusercontent.com/20156968/30717074-319781ae-9ef2-11e7-8e15-b9c8aca3fb2d.png)

**Comment by florenperetti** [comment]
Gracias, ya vi que me faltó una cosa.
